INSERT INTO products (
    product_id,
    name,
    description,
    price,
    stock,
    category,
    main_display,
    seller,
    manufacturer,
    detail_option,
    detail_option_price,
    created_at,
    updated_at
)
VALUES
    (
        9101,
        '제주 햇감귤 3kg',
        '상큼한 산지 직송 감귤 샘플 상품입니다. 이미지는 상품 수정 화면에서 업로드해 주세요.',
        15900,
        120,
        '과일',
        'sale',
        'RefreshMarket 산지직송',
        '제주 감귤 협동조합',
        '기본 3kg, 선물 포장',
        '0,3000',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9102,
        '강원 고랭지 감자 5kg',
        '포슬포슬한 식감의 고랭지 감자 샘플 상품입니다. 대표 이미지를 직접 등록할 수 있습니다.',
        12900,
        85,
        '채소',
        'group',
        'RefreshMarket 산지직송',
        '강원 로컬푸드',
        '기본 5kg, 대용량 10kg',
        '0,9000',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9103,
        '국산 잡곡 10종 세트',
        '현미, 보리, 수수 등 자주 쓰는 잡곡으로 구성한 샘플 상품입니다.',
        21900,
        64,
        '잡곡',
        'promotion',
        'RefreshMarket 큐레이션',
        '우리곡물영농조합',
        '소포장, 가족팩',
        '0,6000',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        9104,
        '프리미엄 토마토 2kg',
        '샐러드와 주스에 모두 쓰기 좋은 토마토 샘플 상품입니다.',
        17900,
        98,
        '채소',
        'sale',
        'RefreshMarket 산지직송',
        '스마트팜 토마토팜',
        '일반, 완숙',
        '0,1500',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT (product_id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    stock = EXCLUDED.stock,
    category = EXCLUDED.category,
    main_display = EXCLUDED.main_display,
    seller = EXCLUDED.seller,
    manufacturer = EXCLUDED.manufacturer,
    detail_option = EXCLUDED.detail_option,
    detail_option_price = EXCLUDED.detail_option_price,
    updated_at = CURRENT_TIMESTAMP;
